DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id PRIMARY KEY NOT NULL,
  username VARCHAR(15) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL,
  is_boolean BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP
);