DROP TABLE IF EXISTS place CASCADE;
CREATE TABLE place (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(40) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  owner_id INTEGER REFERENCES users(id),
  address TEXT NOT NULL,
  latitude VARCHAR(40) NOT NULL,
  longitude VARCHAR(40) NOT NULL
);